ROLE_USER = "USER"
ROLE_ADMIN = "ADMIN"
ROLE_SUPER_ADMIN = "SUPER_ADMIN"

STATUT_PENDING_ACTIVATION = "PENDING_ACTIVATION"
STATUT_MFA_SETUP_REQUIRED = "MFA_SETUP_REQUIRED"
STATUT_ACTIVE = "ACTIVE"
STATUT_DISABLED = "DISABLED"

SESSION_ACTIVE = "ACTIVE"
SESSION_REVOKED = "REVOKED"
SESSION_EXPIRED = "EXPIRED"

TOKEN_ACCOUNT_ACTIVATION = "ACCOUNT_ACTIVATION"
TOKEN_PASSWORD_RESET = "PASSWORD_RESET"
TOKEN_PASSWORD_RESET_FROM_LOCKOUT = "PASSWORD_RESET_FROM_LOCKOUT"

PERMISSION_GERER_UTILISATEURS = "gerer_utilisateurs"
PERMISSION_GERER_DEPARTEMENTS = "gerer_departements"
PERMISSION_GERER_ROLES = "gerer_roles"
PERMISSION_LANCER_ELT = "lancer_traitement_elt"
PERMISSION_CONSULTER_RAPPORTS = "consulter_rapports"

ADMIN_SENSITIVE_PERMISSIONS = {
    PERMISSION_GERER_UTILISATEURS,
    PERMISSION_GERER_DEPARTEMENTS,
    PERMISSION_GERER_ROLES,
    PERMISSION_LANCER_ELT,
}

RISK_LOW = "FAIBLE"
RISK_MEDIUM = "MOYEN"
RISK_HIGH = "ELEVE"
RISK_CRITICAL = "CRITIQUE"

AUDIT_ACTIVATION_LINK_INVALID = "ACTIVATION_LINK_INVALID"
AUDIT_ACCOUNT_ACTIVATION_STARTED = "ACCOUNT_ACTIVATION_STARTED"
AUDIT_PASSWORD_CREATED = "PASSWORD_CREATED"
AUDIT_TOTP_SETUP_STARTED = "TOTP_SETUP_STARTED"
AUDIT_TOTP_SETUP_FAILED = "TOTP_SETUP_FAILED"
AUDIT_TOTP_SETUP_SUCCESS = "TOTP_SETUP_SUCCESS"
AUDIT_ACCOUNT_ACTIVATED = "ACCOUNT_ACTIVATED"

AUDIT_LOGIN_PASSWORD_FAILED = "LOGIN_PASSWORD_FAILED"
AUDIT_ADMIN_LOGIN_PASSWORD_FAILED = "ADMIN_LOGIN_PASSWORD_FAILED"
AUDIT_PASSWORD_VALID_MFA_PENDING = "PASSWORD_VALID_MFA_PENDING"
AUDIT_ADMIN_PASSWORD_VALID_MFA_PENDING = "ADMIN_PASSWORD_VALID_MFA_PENDING"
AUDIT_LOGIN_TOTP_FAILED = "LOGIN_TOTP_FAILED"
AUDIT_ADMIN_LOGIN_TOTP_FAILED = "ADMIN_LOGIN_TOTP_FAILED"
AUDIT_LOGIN_SUCCESS = "LOGIN_SUCCESS"
AUDIT_ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"

AUDIT_SESSION_CREATED = "SESSION_CREATED"
AUDIT_SESSION_ACTIVITY_UPDATED = "SESSION_ACTIVITY_UPDATED"
AUDIT_USER_SESSION_EXPIRED = "USER_SESSION_EXPIRED"
AUDIT_ADMIN_SESSION_EXPIRED = "ADMIN_SESSION_EXPIRED"
AUDIT_USER_LOGOUT = "USER_LOGOUT"
AUDIT_ADMIN_LOGOUT = "ADMIN_LOGOUT"

AUDIT_PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST"
AUDIT_PASSWORD_RESET_REQUEST_UNKNOWN_EMAIL = "PASSWORD_RESET_REQUEST_UNKNOWN_EMAIL"
AUDIT_PASSWORD_RESET_LINK_INVALID = "PASSWORD_RESET_LINK_INVALID"
AUDIT_PASSWORD_RESET_TOTP_FAILED = "PASSWORD_RESET_TOTP_FAILED"
AUDIT_PASSWORD_RESET_RECOVERY_CODE_FAILED = "PASSWORD_RESET_RECOVERY_CODE_FAILED"
AUDIT_PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS"

AUDIT_PASSWORD_RESET_FROM_LOCKOUT_LINK_INVALID = (
    "PASSWORD_RESET_FROM_LOCKOUT_LINK_INVALID"
)
AUDIT_PASSWORD_RESET_FROM_LOCKOUT_TOTP_FAILED = (
    "PASSWORD_RESET_FROM_LOCKOUT_TOTP_FAILED"
)
AUDIT_PASSWORD_RESET_FROM_LOCKOUT_RECOVERY_CODE_FAILED = (
    "PASSWORD_RESET_FROM_LOCKOUT_RECOVERY_CODE_FAILED"
)
AUDIT_PASSWORD_RESET_FROM_LOCKOUT_SUCCESS = "PASSWORD_RESET_FROM_LOCKOUT_SUCCESS"

# Compatibilité avec anciens imports éventuels
USER_SESSION_INACTIVITY_MINUTES = 20
ADMIN_SESSION_INACTIVITY_MINUTES = 15
